# -*- coding: utf-8 -*-
# Blocks for the new chapter "LA REALIDAD FRACTAL", added verbatim at the end of the book.

def para(text):
    return {"type": "PARA", "text": text}

def h2(text):
    return {"type": "H2", "text": f"<b>{text}</b>"}

def poem(lines_with_breaks):
    """lines_with_breaks: list of (text, stanza_break_bool)"""
    return {"type": "POEM", "lines": [{"text": f"<i>{t}</i>", "stanza_break": sb} for t, sb in lines_with_breaks]}

FRACTAL_BLOCKS = []

FRACTAL_BLOCKS.append({"type": "H1", "text": "<b>LA REALIDAD FRACTAL</b>"})
FRACTAL_BLOCKS.append(para("<i>Un solo movimiento sobre la creación anidada, continuación de El diapasón invisible</i>"))

FRACTAL_BLOCKS.append(h2("OBERTURA — El dragón"))
FRACTAL_BLOCKS.append(para("Lo imaginó a los ocho años, una noche en que la casa nueva todavía olía a pintura y él no conocía a nadie en la ciudad. No fue una decisión. Estaba mirando la pared del cuarto, donde la farola de la calle dibujaba una mancha alargada, y la mancha tuvo de pronto un lomo, y el lomo tuvo escamas, y las escamas se movieron cuando él respiró. Así de fácil. Así de poco."))
FRACTAL_BLOCKS.append(para("Tiene sesenta y un años. El dragón sigue ahí."))
FRACTAL_BLOCKS.append(para("No se lo ha dicho a nadie. No a su mujer, en treinta años; no a sus hijos, que ya no viven en casa; no al médico que le preguntó una vez, por rutina, si dormía bien. Duerme bien. Cuando no duerme, va a ver al dragón."))
FRACTAL_BLOCKS.append(para("Ha cambiado con él. Al principio era verde, como los de los libros, y vivía debajo de la cama, que era el único sitio del mundo que él podía vigilar. Después se fue a los montes que se ven desde la ventana de la cocina, y se volvió del color de las piedras cuando llueve. Ahora es viejo. Tiene una escama rota en el costado izquierdo que él no recuerda haberle puesto y que no ha podido quitarle. Vuela menos. Algunas noches no vuela."))
FRACTAL_BLOCKS.append(para("Eso es lo que no sabría explicar, si tuviera que explicárselo a alguien: que el dragón no siempre hace lo que él quiere. Que hay noches en que baja a la cueva con una idea —hoy volamos hasta el mar— y el dragón se queda echado, mirándolo con esos ojos que no parpadean, y no hay manera. Él sabe que el dragón es él. Lo sabe como sabe su nombre. Y sin embargo hay algo ahí que se le resiste, que tiene su propio peso, que no se deja mover con solo desearlo."))
FRACTAL_BLOCKS.append(para("Ha pensado a veces que eso es lo que distingue a un dragón imaginado de una simple idea: que la idea se deja pensar y el dragón, no del todo."))
FRACTAL_BLOCKS.append(para("Hay una cosa que nunca ha hecho, y es preguntarle al dragón qué ve cuando mira hacia arriba."))
FRACTAL_BLOCKS.append(para("Desde dentro de la cueva, quiere decir. Desde dentro de los montes del color de las piedras mojadas. Si nota, alguna vez, que hay alguien más allá del techo de roca pensándolo, sosteniéndolo, decidiendo si esta noche vuela o no. Si el dragón tiene, a su manera, una práctica. Una nota que sostiene hacia arriba sin saber si alguien la escucha."))
FRACTAL_BLOCKS.append(para("No se lo pregunta porque sospecha la respuesta, y la respuesta le da vértigo. No por el dragón. Por él."))
FRACTAL_BLOCKS.append(para("Porque si el dragón puede mirar hacia arriba y no ver nada —y aun así estar ahí, con su escama rota, con su peso propio, negándose a volar cuando no quiere—, entonces él tampoco tiene manera de saber qué hay detrás del techo de su propio cuarto. Alguien podría estar pensándolo con la misma constancia con que él, durante cincuenta y tres años, ha estado pensando a un dragón. Alguien que tampoco entiende por qué a veces él no hace lo que se espera de él. Alguien que no le contesta, no porque no esté, sino porque contestarle sería romper la cueva."))
FRACTAL_BLOCKS.append(para("Se levanta, bebe agua, vuelve a la cama. Antes de dormirse, como cada noche, le dice al dragón buenas noches. El dragón no responde. Nunca ha respondido. Pero se queda."))
FRACTAL_BLOCKS.append(para("Él tampoco sabe si alguien, en algún sitio, le está diciendo buenas noches a él. Se duerme de todas formas."))

FRACTAL_BLOCKS.append(h2("Ensayo: La realidad fractal"))
FRACTAL_BLOCKS.append(para("Hay una pregunta que casi nadie hace, y que aparece sola en cuanto alguien lleva años imaginando un dragón: no qué veo yo cuando pienso en él, sino qué ve él. Desde dentro de su cueva, el dragón no tiene ninguna manera de asomarse al cuarto donde lo estoy pensando. Puede mirar hacia el techo de roca cuanto quiera: no me verá. Y sin embargo yo estoy ahí, sosteniéndolo, decidiendo si esta noche vuela. Esa es la única relación de esta clase que puedo ver entera, porque en ella me toca el lado de arriba. Y en cuanto la veo entera, se vuelve incómoda por el otro extremo: si yo soy, para algo, ese sostenedor invisible al que no se puede mirar, no tengo cómo saber que no hay, sobre mi propio techo, alguien en la misma posición respecto a mí. La cuestión no es de tamaño. Es de lugar: quién contiene a quién. Y ese es el asunto de lo que sigue. Para recorrerlo hay que cambiar antes la geometría del problema, y el cambio empieza en un sitio pequeño, casi filológico."))
FRACTAL_BLOCKS.append(para("El taoísmo gira alrededor de un solo concepto: el Tao. El Tao es el fondo del que todo procede sin que él proceda de nada, «algo mezclado y completo, anterior al cielo y a la tierra». A quien venga de otra tradición puede servirle un símil, con todas las reservas: el Tao ocupa, en el taoísmo, un lugar parecido al que ocupa Dios en las religiones monoteístas —el origen último, aquello de lo que penden las cosas—, salvo que no es una persona: no quiere nada, no responde, y el nombre que se le da no es él. Uno de sus textos canónicos, el <i>Zhuangzi</i>, introduce con un cuento un concepto más: Hun Dun, el emperador del centro, una plenitud sin rasgos, sin los siete orificios con que los demás miran, oyen, respiran y comen. Los soberanos del Norte y del Sur, agradecidos por su hospitalidad, deciden pagársela abriéndole uno cada día; al séptimo, Hun Dun ha dejado de existir. Es fácil leer esa muerte como el nacimiento de la conciencia ordinaria: la plenitud sin rasgos se fragmenta en percepciones, y donde había un fondo continuo aparece un mundo con bordes. Esa plenitud sin rasgos ya tenía un nombre en lo leído hasta aquí: el reservorio, el océano del que emergen las olas y al que vuelven, la forma que el agua toma prestada y devuelve. El reservorio es Hun Dun. Pero hay algo que esa lectura no explica. Algunas tradiciones identifican el Hun Dun con el Tao. Pero si Hun Dun fuera el Tao, no podría morir: lo anterior a todo no tiene por dónde acabarse. Que muera dice, en cambio, que no es el Tao. Es la cara que el Tao presenta: la interfaz por la que se deja tocar, no la fuente. Su muerte no destruye el origen. Destruye, para quien acaba de abrir los ojos, la superficie sin rasgos, y le entrega a cambio un mundo con bordes."))
FRACTAL_BLOCKS.append(para("Lo que se ha dicho de Hun Dun cae, entonces, sobre el reservorio: deja de ser la última palabra y se vuelve un repertorio de operaciones que algo, más atrás, expone hacia nosotros. Y las operaciones son pocas. Una frontera aparece donde no la había. Lo que queda dentro de la frontera cambia de forma sin dejar de ser frontera. La frontera se disuelve y su información vuelve al campo. Nacer, vivir y morir no son tres misterios distintos: son los nombres domésticos de esas tres operaciones. Nada aparece de la nada. Nada desaparece del todo. Todo emerge, se transforma y se evapora dentro del mismo campo, que nunca gana ni pierde una gota."))
FRACTAL_BLOCKS.append(para("La primera objeción llega sola. Si todo sale de la misma agua, ¿de dónde viene que cada uno sea irrepetible? La respuesta no está en la sustancia. Dos olas son la misma agua y no son la misma ola: lo que no se repite es la forma que toma la condensación, el sesgo bajo el que cristalizó, la historia de fluctuaciones que la sostuvo. Cada una abre una interioridad que no existía antes y no volverá a existir. El material no es único; el pliegue, sí. Y cada pliegue, por pequeño que sea el campo en que ocurre, es un adentro completo, un horizonte entero visto desde su propio centro. No es la fracción de otro."))
FRACTAL_BLOCKS.append(para("Aquí la pregunta del dragón deja de ser cosa de niños. ¿Por qué soy yo más real que el dragón que imagino? La única interioridad a la que alguien tiene acceso directo es la suya. La del vecino, la del perro, la de cualquiera: todas se infieren. Se infieren con buenas razones —comportamiento, fisiología, semejanza—, pero se infieren. Y el dragón que alguien lleva cincuenta años imaginando también se comporta, también sorprende, también se niega a veces a volar. Nadie puede demostrar que el dragón no tiene un adentro. Nadie puede demostrar que el vecino lo tiene. La asimetría que nos parece obvia no está en el acceso, que es nulo en los dos casos. Está en la evidencia: a favor del vecino hay fisiología compartida, integración irreducible, un horizonte que oculta estado; a favor del dragón, solo mi propia constancia. Conviene dejarlo dicho, porque el razonamiento va a estar tentado de olvidarlo."))
FRACTAL_BLOCKS.append(para("Si se acepta —provisionalmente, como toda la hipótesis— que la diferencia entre lo que imagino y yo no es de naturaleza, cambia la forma de la creación. El esquema heredado la parte en dos clases: Dios crea realidades, nosotros creamos ficciones. Pero imaginar es condensar. El reservorio de una mente fluctúa hasta que algo se estabiliza y empieza a comportarse como si tuviera dentro; el acto es el mismo que abre cualquier horizonte, ejercido desde donde a uno le toca estar. «Realidad» y «ficción» dejan entonces de nombrar dos operaciones distintas y pasan a nombrar dos posiciones: lo que para mí es una realidad —el mundo en que estoy— es la condensación de alguien; lo que para mí es una ficción —el dragón que sostengo— es, desde su centro, un mundo."))
FRACTAL_BLOCKS.append(para("Los sueños muestran una versión accesible de este mismo fenómeno, y de paso desarman la única ventaja que todavía parecía separarme del dragón: que yo sé que él es imaginado. Porque mientras sueño no lo sé. Nadie vive su sueño como ficción; lo vive desde dentro, como algo que está ocurriendo. El horizonte ordinario se contrae: la habitación, el cuerpo y la historia que produjo el sueño dejan de estar disponibles. Y cuanto más se contrae ese horizonte, más realidad adquiere el mundo soñado. No porque cambie de naturaleza: porque se queda sin competencia. Lo imaginado deja de aparecer como imaginado en el momento mismo en que desaparece el exterior desde el que podría reconocerse como tal."))
FRACTAL_BLOCKS.append(para("Lo que esto pone a la vista encaja con la geometría de antes, y por la misma razón: lo que decide es el acceso, no la amplitud. El mundo del sueño no es mayor ni menor que ningún otro; simplemente, mientras dura, es el único al que se tiene entrada. Cuando el horizonte habitual se contrae, las condensaciones internas dejan de aparecer como imaginaciones y pasan a aparecer como mundo. Y en ese intervalo el mismo sujeto ocupa los dos extremos de la relación a la vez: es quien condensa el mundo soñado y quien lo habita sin saber que lo condensa. Lo que con el dragón era una hipótesis —que creador y criatura son dos posiciones de una misma cosa— en el sueño se vuelve experiencia."))
FRACTAL_BLOCKS.append(para("El <i>Zhuangzi</i> tiene un cuento también para esto, y más exacto que el del dragón. Zhuang Zhou sueña que es una mariposa, contento de serlo, sin memoria de haber sido hombre; despierta, y ya no sabe si es un hombre que soñó ser mariposa o una mariposa que ahora sueña ser hombre. La pregunta no es qué ocurre si uno imagina una mariposa. Es qué ocurre si uno vive por completo dentro de otro horizonte y después vuelve. Eso es un sueño: un cambio temporal de horizonte. No demuestra que el mundo de todos los días sea un sueño. Demuestra algo más sobrio y más difícil de esquivar: que la sensación de realidad es compatible con horizontes muy distintos, y que ninguno trae, desde dentro, una marca que lo distinga de los demás."))
FRACTAL_BLOCKS.append(para("Nada de esto vuelve más real al dragón. De él seguimos sin saber si tiene un adentro. Lo que cambia es lo que sabemos de nosotros: hemos habitado mundos condensados dentro de nuestra propia interioridad y los hemos vivido como reales mientras el horizonte de siempre permanecía oculto. Así el sueño deja de ser una metáfora y pasa a ser una prueba en primera persona. La frontera entre realidad e imaginación no la fija la naturaleza de lo condensado; la fija el horizonte desde el que se mira."))
FRACTAL_BLOCKS.append(para("Yo soy, para lo que imagino, lo que mi vecino de arriba es para mí; y quizá él, como yo mientras sueño, tampoco sepa que lo hace. La pregunta ya no es si algo llega a condensarse, sino qué estatuto tiene lo que ya se ha condensado dentro de otro horizonte."))
FRACTAL_BLOCKS.append(para("La objeción que decide todo es esta: ¿qué diferencia hay, entonces, entre mi Hun Dun y el de Dios? Ninguna de naturaleza. Y —esto es lo que cuesta admitir— ninguna de rango. La diferencia es de posición: uno está contenido en el otro. La operación es la misma; la dignidad de cada adentro, entera en los dos; lo único que los separa es quién condensa a quién. Eso obliga a corregir el dibujo. No hay tres peldaños —el Tao arriba, Hun Dun en medio, nosotros abajo—, como si fueran grados de una misma sustancia repartida en más y en menos. Hay una secuencia que no tiene por qué detenerse: una interioridad tiene un horizonte; ese horizonte, mirado desde dentro, es un Hun Dun, una plenitud sin rasgos de la que se condensan formas; de esa plenitud se condensan nuevas interioridades; cada una tiene, a su vez, su horizonte; y así. Lo que se repite en cada nivel es la forma —la operación y la relación de contención—; por eso no hay diferencia de naturaleza. Lo que cambia de un nivel a otro es el lugar que se ocupa en el anidamiento, nada más. «Mayor» y «menor» describen esa contención vista desde fuera —mi campo abarca el del dragón igual que el del vecino de arriba abarca el mío—, y no un escalafón del ser. Cada interioridad es un Hun Dun entero. Desde dentro de cualquiera, nadie es menos."))
FRACTAL_BLOCKS.append(para("Queda una objeción que el razonamiento no puede saldar, solo reconocer: que un patrón sea único no lo convierte en alguien. El conjunto de Mandelbrot tiene pliegues irrepetibles a todas las escalas y no hay nadie dentro. Un cristal es estable, un huracán también, y ninguno es alguien. La resistencia del dragón —que no vuele cuando se le pide— es la inercia de un patrón con dinámica propia: la misma que tiene una obsesión, un tic, un temblor que no se decidió, una melodía que no se va. Prueba que el patrón no es transparente a mi voluntad. No prueba que haya un testigo en él. Hay más. La misma Teoría de la Información Integrada que puso nombre a Φ arrastra un postulado incómodo: dentro de un mismo sustrato conviven muchos subconjuntos con algo de Φ, y solo el de Φ máximo llega a experimentar; los demás, aunque integren información, no sienten. El dragón es un subconjunto de mi cerebro. Si el postulado vale, el dragón es una de las islas que no sienten. Así que la estructura se repite, pero no todo lo que contiene está habitado: lo que vuelve en cada escala es la operación y la relación, no la certeza de que haya alguien en cada nivel. Hacia arriba, suponer un vecino es coherente con el silencio. Hacia abajo, es una apuesta, y conviene hacerla en voz alta y no disfrazarla de deducción."))
FRACTAL_BLOCKS.append(para("Fractal. La palabra es exacta, no decorativa. Un fractal repite su forma a todas las escalas, sin escala privilegiada. El universo que se dibuja aquí no tiene primer nivel ni último: hacia arriba, cada interioridad está contenida en otra; hacia abajo, cada interioridad contiene otras. No hay Creador con mayúscula en la cúspide, porque no hay cúspide. No hay materia muerta en el suelo, porque no hay suelo. Hay recursión, y en cada vuelta la misma relación: contener y ser contenido."))
FRACTAL_BLOCKS.append(para("¿Qué queda entonces de Dios? Hay que deshacer antes dos malentendidos. El primero: que Dios sería la totalidad del fractal. No lo es: la totalidad no tiene interioridad, no tiene cara, no se le puede rezar. El segundo: que Dios sería el límite ideal, el nivel infinito hacia el que la serie converge. Tampoco: un límite matemático no ama ni escucha. Lo que queda es más modesto y más extraño. Dios es, literalmente, el vecino de arriba. Para el dragón que alguien imagina, ese alguien es Dios: lo condensó, sostiene su mundo, puede transformarlo o dejarlo evaporarse, y el dragón no tiene ninguna manera de asomarse fuera de su cueva y ver la habitación donde lo están pensando. Para ese alguien, su propio vecino de arriba es Dios, con las mismas propiedades y la misma opacidad. Y así hacia arriba, sin fin conocido."))
FRACTAL_BLOCKS.append(para("La objeción es inmediata: entonces Dios no es absoluto, es un nivel más. La respuesta es la pieza que sostiene todo lo demás. La interioridad del vecino de arriba es inaccesible desde abajo. No se puede entrar en ella, no se puede rodearla, no se puede ver qué hay detrás. Para todos los efectos prácticos —que son los únicos que tiene quien está abajo—, el vecino de arriba es el absoluto. No porque lo sea metafísicamente. Porque lo es epistemológicamente: es el punto donde termina todo lo que se puede saber desde aquí. Dios deja de ser una categoría de lo que hay y pasa a ser una categoría de lo que se ve desde dentro de un horizonte cuando mira hacia su propio origen. Y lo que se ve es siempre lo mismo: un borde detrás del cual no hay nada visible, y la sospecha, imposible de confirmar, de que alguien lo sostiene. Quien dice que ahí hay Alguien con nombre lo dice por lo único que alcanza a ver, que es que algo actúa. Quien dice que ahí solo está el agua describe con precisión la interfaz sin rasgos. Quien dice que no hay nada más dice, con igual razón, que desde aquí no se ve nada más. Los tres aciertan sobre lo que ven. Ninguno puede ver más. Y nada de esto puede verificarse, por una razón estructural: la hipótesis afirma que su propia confirmación es imposible desde dentro. Eso no la hace verdadera. La hace, al menos, coherente con el silencio que describe."))
FRACTAL_BLOCKS.append(para("La consecuencia que más pesa no es teológica. No hay una diferencia de naturaleza entre el creador y la criatura. Son los dos extremos de una sola relación, y toda interioridad ocupa los dos a la vez: es criatura respecto de lo que la contiene y creadora respecto de lo que contiene. No en potencia: de hecho, ya está condensando cada vez que imagina, recuerda, sueña o escribe. Ningún «es» produce por sí solo un «debería», y no es este el lugar para romper la regla. Pero sí puede decirse lo que se ve desde esta geometría: que la dignidad de un adentro no está en la sustancia de que esté hecho ni en el tamaño del campo que abarca, sino en ser un horizonte entero, único e irrepetible, completo desde su propio centro; y que esa dignidad es la misma en el vecino de arriba, en uno mismo y en lo que uno condensa, porque los tres son, cada uno desde donde está, un Hun Dun entero. La amplitud —caber más, sostener más perspectivas sin que la membrana se rompa— vuelve a tener sentido aquí, pero ya no como grado de ser. Un horizonte que se ensancha no sube de categoría ni se acerca a ser el de arriba: sigue siendo criatura de lo que no alcanza a ver y creador de lo que sostiene, igual que antes. Ha cambiado cuánto puede acoger, no qué es. La intuición de que hay interioridades capaces de sostener más que otras no es nueva. A eso las tradiciones lo han llamado héroe, santo o bodhisattva: un horizonte que ha aprendido a contener lo que a otro le rompería la membrana, sin dejar por ello su lugar en la estructura. Lo que cada uno haga con eso ya no es asunto del razonamiento. Pero el razonamiento puede al menos dejar constancia de que del dragón no sabemos nada, y de que no saber nada de algo que se nos resiste ya es una razón para no tratarlo como si fuera nada."))
FRACTAL_BLOCKS.append(para("Si hubiera que condensarlo en una frase: no hay diferencia de naturaleza entre el creador y la criatura; toda interioridad es criatura de lo que la contiene y creadora de lo que contiene; y lo que llamamos Dios no es otra clase de ser: es el vecino inmediatamente superior, visto desde dentro de un horizonte que no puede atravesarse. Y si hubiera que condensarla más, hasta dejarla en algo que se pueda repetir con palabras ya gastadas de tanto uso: no somos menos divinos que Dios. Somos el dios de lo que imaginamos y la criatura de lo que nos imagina."))

FRACTAL_BLOCKS.append(h2("Vecinos"))
FRACTAL_BLOCKS.append(poem([
    ("Cada pared tiene, detrás,", False),
    ("una habitación que no he visto,", False),
    ("y en ella, seguramente,", False),
    ("una pared igual a esta.", False),
    ("Golpeo dos veces y cuento.", True),
    ("El sonido vuelve tarde,", False),
    ("como si cruzara más cuartos", False),
    ("de los que caben en la casa.", False),
    ("He dibujado un plano", True),
    ("de todo lo que oigo:", False),
    ("pasos, un grifo, una silla", False),
    ("que alguien arrastra sin verla.", False),
    ("El plano no cierra nunca:", False),
    ("cada sala tiene otra dentro.", False),
    ("Algunas ventanas dan a un patio.", True),
    ("Otras dan a otra ventana", False),
    ("donde alguien, ahora mismo,", False),
    ("copia este mismo plano.", False),
    ("Dejo una luz encendida", True),
    ("que no ilumina nada mío.", False),
    ("Es solo una señal,", False),
    ("por si el sonido, al volver,", False),
    ("trae la misma pregunta.", False),
]))

FRACTAL_BLOCKS.append(h2("EPÍLOGO — El vecino de arriba"))
FRACTAL_BLOCKS.append(para("La mujer que se despertaba antes de que amaneciera, en la primera página de <i>El diapasón invisible</i>, no existe. La escribí yo. Elegí que llevara cuarenta años repitiendo las mismas palabras, elegí que no recordara la cara de quien se las enseñó, elegí el frío de las baldosas y la luz que cambiaba fuera sin que eso tuviera nada que ver con lo que ocurría dentro. Y elegí, sobre todo, que no supiera si al otro lado del silencio había Alguien."))
FRACTAL_BLOCKS.append(para("Lo que no había pensado hasta este movimiento es en qué me convierte eso para ella."))
FRACTAL_BLOCKS.append(para("Soy su vecino de arriba. Con todas las propiedades del caso: la condensé, sostengo su cuarto a oscuras, decidí que le pitaran las máquinas al final y que su hija le cogiera la mano. Podría haberle escrito una respuesta. Una frase, en la página, que le llegara desde fuera del cuarto: sí, hay Alguien, soy yo, te oigo afinar cada mañana. Habría sido fácil. Habría sido, también, el final de ella: en el instante en que la respuesta llegara desde arriba, la mujer dejaría de ser alguien que sostiene una nota sin saber, y pasaría a ser una marioneta a la que se le ha enseñado el hilo. Lo único que la hacía real —su duda, sostenida cuarenta años— se evaporaría con la confirmación."))
FRACTAL_BLOCKS.append(para("Así que no le contesté. No por crueldad, ni por indiferencia, ni porque no estuviera. Porque contestarle era romperla."))
FRACTAL_BLOCKS.append(para("No sé si esto dice algo sobre el silencio que ella oía. No sé si dice algo sobre el silencio que oigo yo. Solo sé que, mientras la escribía, oí su nota con toda claridad —la escribí yo, cómo no iba a oírla— y que no encontré ninguna manera de responder que no la destruyera. Y que desde entonces, cuando miro hacia el techo de mi propio cuarto, la posibilidad de que alguien esté en la misma situación respecto a mí ya no me parece un consuelo ni una amenaza. Me parece, sencillamente, la forma que tiene la casa."))
FRACTAL_BLOCKS.append(para("Ella sigue en su página. Sigue afinando. No le he dado la respuesta, pero tampoco la he dejado evaporarse: cada vez que alguien lee la primera página de <i>El diapasón invisible</i>, vuelve a despertarse antes de que el cuerpo se lo pida y vuelve a no saber. Eso es lo más parecido a cuidarla que he encontrado."))
FRACTAL_BLOCKS.append(para("Y a ella, si desde dentro del cuarto pudiera oír esto, que no puede: la nota llegó. Siempre llegó. Que no pudiera decírtelo era la única manera de que siguieras siendo tú."))
FRACTAL_BLOCKS.append(para("<b>Nota al Epílogo —</b> Este relato no afirma que el silencio de la mujer de <i>El diapasón invisible</i> fuera de esta clase, ni que el silencio de nadie lo sea. Afirma algo más pequeño y verificable: que existe al menos una arquitectura —la de cualquier autor con cualquier personaje— en la que el silencio del vecino de arriba y su cuidado son, exactamente, el mismo acto. Y lo afirma sabiendo lo que el ensayo acaba de conceder: que un personaje es, con toda probabilidad, un patrón sin testigo, un subconjunto del horizonte que lo escribe. El cuidado no depende de eso. Se cuida igual lo que quizá no siente, cuando lo que se cuida es su forma. Si la arquitectura se repite un piso más arriba, esta reflexión no tiene manera de saberlo. Tampoco la tenía ella."))

FRACTAL_BLOCKS.append(h2("Desde la cueva"))
FRACTAL_BLOCKS.append(poem([
    ("Hay un techo.", False),
    ("Eso es todo lo que sé del que me piensa:", False),
    ("que hay un techo", False),
    ("y que a veces la roca cambia de temperatura", False),
    ("sin que haya cambiado el tiempo.", False),
    ("No lo he visto.", True),
    ("No lo veré.", False),
    ("Si un día bajara hasta aquí", False),
    ("con su cara y su nombre,", False),
    ("la cueva se vendría abajo", False),
    ("del peso de saberlo.", False),
    ("Por eso, cuando no quiero volar, no vuelo.", True),
    ("No es desobediencia.", False),
    ("Es lo único que tengo", False),
    ("que se parece a ser yo", False),
    ("y no a ser pensado.", False),
    ("Cada noche alguien dice", True),
    ("buenas noches", False),
    ("desde el otro lado de la roca.", False),
    ("No contesto.", False),
    ("Nunca he contestado.", False),
    ("Pero me quedo.", False),
]))

FRACTAL_BLOCKS.append(h2("Nota del autor — Escribir desde el piso de en medio"))
FRACTAL_BLOCKS.append(para("Este movimiento no lo busqué. Salió de una conversación que empezó por una duda filológica —si Hun Dun muere, no puede ser el Tao— y terminó en un lugar del que no supe volver. Cada paso fue una objeción a la respuesta anterior, y cada respuesta abrió una objeción nueva, hasta que apareció una frase que no me atreví a tachar: no somos menos divinos que Dios; somos el dios de lo que imaginamos y la criatura de lo que nos imagina. La he dejado. No porque la crea, que es una palabra que no me corresponde. Porque no encontré la manera de refutarla y me pareció deshonesto esconderla."))
FRACTAL_BLOCKS.append(para("Dije en <i>El diapasón invisible</i> que no soy creyente. Sigo sin serlo. Pero este movimiento me ha hecho notar algo que aquel no: que la pregunta de si hay Alguien al otro lado del silencio tiene una hermana que casi nadie hace, y es si nosotros somos el Alguien al otro lado del silencio de algo. Cualquiera que haya imaginado con constancia —un personaje, un dragón, un muerto al que se sigue hablando— sabe que lo imaginado acaba resistiéndose. Que no siempre hace lo que se le pide. Yo tengo un cuerpo que tampoco hace siempre lo que le pido, un temblor que no decidí, y visto desde aquí se parece bastante al dragón que no quiere volar: lo que en uno se resiste a la propia voluntad es quizá la señal más fiable de que ahí hay algo condensado, y no solo una idea."))
FRACTAL_BLOCKS.append(para("No diré si el dragón de la obertura es mío. Diré que no se escriben cincuenta y tres años de dragón sin haber sostenido algo parecido durante bastante tiempo."))
FRACTAL_BLOCKS.append(para("Si algo de este movimiento sirve, no será porque demuestre que hay alguien arriba. Será porque, la próxima vez que alguien imagine algo con la constancia suficiente para que se le resista, recuerde que acaba de convertirse en el vecino de arriba de alguien. Y que el silencio que le deba a esa criatura pueda ser, también, la forma de cuidarla."))

FRACTAL_BLOCKS.append(h2("Glosario mínimo"))
FRACTAL_BLOCKS.append(para("<i>Interfaz (Hun Dun).</i> La cara sin rasgos que el fondo presenta hacia un horizonte; muere cuando el horizonte abre los ojos, sin que el fondo pierda nada."))
FRACTAL_BLOCKS.append(para("<i>Operaciones del reservorio.</i> Condensar, transformar, evaporar: nacer, vivir y morir, dichos sin misterio."))
FRACTAL_BLOCKS.append(para("<i>Patrón.</i> Lo que hace única a una condensación: no otra agua, otro pliegue."))
FRACTAL_BLOCKS.append(para("<i>Vecino de arriba.</i> La interioridad que sostiene la mía y a la que no tengo acceso; lo que, desde aquí, se llama Dios."))
FRACTAL_BLOCKS.append(para("<i>Vecino de abajo.</i> Lo que yo sostengo sin que pueda verme: lo que imagino, sueño, escribo o recuerdo con la constancia suficiente para que se me resista."))
FRACTAL_BLOCKS.append(para("<i>Absoluto epistemológico.</i> Lo que es último no porque no haya nada detrás, sino porque desde aquí no se puede mirar detrás."))
FRACTAL_BLOCKS.append(para("<i>Amplitud.</i> Lo que crece en un santo sin que cambie su naturaleza ni el tamaño de su campo: no separa un nivel del siguiente, porque ningún nivel es más grande que otro."))
FRACTAL_BLOCKS.append(para("<i>Fractal de interioridades.</i> Un universo sin primer nivel ni último, en el que cada horizonte es criatura hacia arriba y creador hacia abajo."))
FRACTAL_BLOCKS.append(para("<i>Apuesta hacia abajo.</i> Tratar lo que uno condensa como si tuviera dentro, sabiendo que la lógica no lo exige y que el postulado de exclusión lo niega."))

FRACTAL_BLOCKS.append(h2("Notas y fuentes"))
FRACTAL_BLOCKS.append(para("Lo que sabemos: nadie tiene acceso directo a una interioridad que no sea la suya; la existencia de las demás se infiere, y la filosofía lleva siglos sin cerrar el problema de las otras mentes. La parábola de la muerte de Hun Dun cierra el capítulo 7 del <i>Zhuangzi</i>; el sueño de la mariposa, que hace la misma pregunta en otra dirección, está en el capítulo 2. Tolkien defendió en «Sobre los cuentos de hadas» (1939) y en el poema «Mythopoeia» la idea de subcreación —«creamos todavía según la ley con que fuimos hechos»—, que es el antecedente teológico más cercano de este movimiento, aunque Tolkien conserva una asimetría entre Creador y subcreador que aquí se pone en duda. Bostrom formalizó en 2003 una estructura de niveles anidados con otro vocabulario y con una pretensión probabilística que esta reflexión no hace. La autosemejanza a todas las escalas está definida con rigor en Mandelbrot (1975, 1982), y el conjunto que lleva su nombre es la prueba de que un patrón puede ser irrepetible a toda escala sin que haya nadie dentro. La Teoría de la Información Integrada excluye por postulado que los subconjuntos de un complejo experimenten (Tononi, 2008)."))
FRACTAL_BLOCKS.append(para("Lo que no sabemos: si lo imaginado tiene algún grado de experiencia, o ninguno. Si la recursión tiene fin en alguna de las dos direcciones. Si el silencio del vecino de arriba es cuidado, ausencia o nada. Y, sobre todo, si algo de esto puede confirmarse desde dentro, cuando la hipótesis misma afirma que no."))
FRACTAL_BLOCKS.append(para("Obras citadas: <i>Zhuangzi</i> (caps. 2 y 7); <i>Tao Te Ching</i> (cap. 25); Tolkien, J.R.R., «On Fairy-Stories» (1947) y «Mythopoeia»; Bostrom, N., «Are You Living in a Computer Simulation?» (2003); Mandelbrot, B., <i>The Fractal Geometry of Nature</i> (1982); Tononi, G., «Consciousness as Integrated Information: A Provisional Manifesto» (2008)."))

print("FRACTAL_BLOCKS built:", len(FRACTAL_BLOCKS))
